apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-k8s-service-deployment
  labels:
    app: booking-k8s-service
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: booking-k8s-service
  template:
    metadata: 
      labels:
        app: booking-k8s-service
    spec:
      containers:
      - name: booking-k8s-service
        image: vittoriapac/booking-service
        ports:
        - containerPort: 10443